### PR TITLE
:bug: fix(a11y): make aria-label text less redundant for anchors

### LINKED ISSUE #63: Accessibility: Is the aria-label text too redundant?
Someone just notified me that the `aria-label` for the anchor links is kind of redundant in screenreaders.

For example, if I use a heading `<h3>My heading</h3>`, the anchor link for that will get `aria-label="Anchor link for: my heading"`, which seems to (I'm not a screenreader user myself) be read as something like “Heading level 3 My heading Anchor link for: my heading" in at least some screenreader/browser combinations.

My suggestion would be to reduce the default `aria-label` to something like “Permalink”, “Link to this” or something like that? Also, you might want to make this label text configurable for i18n.

### PR DESCRIPTION
**Pull request by bryanbraun**
Fixes #63

### CODE REVIEW

File: anchor.js [hunk 1]
```diff
@@ -134,11 +134,11 @@
         readableID = elementID.replace(/-/g, ' ');
 
         // The following code builds the following DOM structure in a more effiecient (albeit opaque) way.
-        // '<a class="anchorjs-link ' + this.options.class + '" href="#' + elementID + '" aria-label="Anchor link for: ' + readableID + '" data-anchorjs-icon="' + this.options.icon + '"></a>';
+        // '<a class="anchorjs-link ' + this.options.class + '" href="#' + elementID + '" aria-label="Anchor" data-anchorjs-icon="' + this.options.icon + '"></a>';
         anchor = document.createElement('a');
         anchor.className = 'anchorjs-link ' + this.options.class;
         anchor.href = '#' + elementID;
-        anchor.setAttribute('aria-label', 'Anchor link for: ' + readableID);
+        anchor.setAttribute('aria-label', 'Anchor');
```
Comment (tmorehouse) [inline anchor.js]: I would suggest the aria-label text be configurable via an option so that it could support multiple languages.

Comment (bryanbraun) [reply anchor.js]: Good idea. Let me see what I can do here.

Comment (tmorehouse) [reply anchor.js]: if you had `options.ariaLabel`, then you could test to see if it is `truthy`, and if it is, then set the `aria-label` attribute, otherwise don't add it at all.

```js
if (this.options.ariaLabel) {
  anchor.setAttribute('aria-label',this.options.ariaLabel);
}
```

**Comment by bryanbraun** [comment]
@tmorehouse, the latest commit adds the option you described, along with tests and docs.
